heroku/buildpacks-jvm

.circleci/config.yml, README.md, buildpacks/maven/CHANGELOG.md, buildpacks/maven/README.md, buildpacks/maven/bin/build, buildpacks/maven/bin/detect, buildpacks/maven/buildpack.toml, buildpacks/maven/lib/common.sh, buildpacks/maven/lib/frameworks.sh, buildpacks/maven/lib/maven.sh, buildpacks/maven/lib/v3/buildpack.sh, buildpacks/maven/lib/v3/common.sh, buildpacks/maven/package.toml, meta-buildpacks/java/buildpack.toml, meta-buildpacks/java/package.toml, test/rapier/rapier.rb
This is a copy of the already existing `heroku/maven` buildpack that can be found here: https://github.com/heroku/heroku-buildpack-java/ with the following differences:
- Removed V2 buildpack support
- Applied `shfmt` to shell source files
- Fixed most `shellcheck` issues (I suppressed two where the code will be replaced very soon anyway)
The intent is to continue development on the CNB portion in this repo and remove CNB support from the V2 repo. This untangles the sources, allowing for higher development velocity and sane release management.
=> Add heroku/maven

common/meta-build.sh
`meta-build.sh` currently fails if not all dependencies also have a build script. Backport of https://github.com/heroku/buildpacks-node/pull/13/commits/f89d443863c4ba7ba2fee1d63eac9452772f2ff3.
=> Fix meta-build.sh

shimmed-buildpacks/clojure/CHANGELOG.md, shimmed-buildpacks/clojure/buildpack.toml, shimmed-buildpacks/gradle/CHANGELOG.md, shimmed-buildpacks/gradle/buildpack.toml, shimmed-buildpacks/scala/CHANGELOG.md, shimmed-buildpacks/scala/buildpack.toml, test/meta-buildpacks/java/buildpack.toml
Related to [W-8925222](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B00000097HLvIAM/view)
=> Update shimmed buildpacks

meta-buildpacks/java/README.md
[README.md](https://github.com/heroku/buildpacks-jvm/blob/1c4de6a4204de1ae2c12116a9b1fe44fbaced755/meta-buildpacks/java/README.md)
Closes [W-8961220](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B0000008wyuzIAA/view)
=> Add README for heroku/java

shimmed-buildpacks/scala/CHANGELOG.md, shimmed-buildpacks/scala/buildpack.toml
Based on `v90` of the classic Heroku buildpack.
Closes [W-8981150](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B0000008xI0HIAU/view)
=> heroku/scala 0.0.90

meta-buildpacks/java/CHANGELOG.md, meta-buildpacks/java/buildpack.toml, meta-buildpacks/java/package.toml, test/meta-buildpacks/java/buildpack.toml, test/meta-buildpacks/java/package.toml, test/specs/maven/spec_helper.rb
Closes [W-9005304](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B0000008xZt8IAE/view)
=> Bump heroku/procfile to 0.6.2

buildpacks/jvm/CHANGELOG.md, buildpacks/jvm/lib/jvm.sh
Mirror PR for https://github.com/heroku/heroku-buildpack-jvm-common/pull/204
=> Add support for Java 16

buildpacks/jvm-function-invoker/CHANGELOG.md, buildpacks/jvm-function-invoker/bin/detect, buildpacks/jvm-function-invoker/lib/toolbox.sh
See https://salesforce.quip.com/tLL9AiScqg5q for the schema (Salesforce internal link). Sadly, I don't have a public link atm.
=> update jvm-function-invoker detect for new project.toml schema changes

buildpacks/jvm-function-invoker/CHANGELOG.md, buildpacks/jvm-function-invoker/buildpack.toml
References [GUS-W-9298590](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07AH000000MP71YAG/view)
=> Update sf-fx-runtime-java to 0.2.4

.github/workflows/release.yml
Closes [GUS-W-9606750](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07AH000000RITaYAO/view)
=> Install Rust dependencies during release

buildpacks/maven/bin/build
=> Remove dep-tracker

buildpacks/jvm-function-invoker/CHANGELOG.md, buildpacks/jvm-function-invoker/buildpack.toml
Changelog:
https://github.com/forcedotcom/sf-fx-runtime-java/compare/1.0.0...1.0.1
Refs GUS-W-9809145.
=> Update JVM function runtime to 1.0.1

buildpacks/jvm/CHANGELOG.md, buildpacks/jvm/lib/jvm.sh
Mirror PR for [jvm-common](https://github.com/heroku/heroku-buildpack-jvm-common/pull/214).
References [W-8655975](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B0000008vpiZIAQ/view)
=> Add support for OpenJDK 17

buildpacks/jvm-function-invoker/CHANGELOG.md, buildpacks/jvm-function-invoker/buildpack.toml
https://github.com/forcedotcom/sf-fx-runtime-java/compare/1.0.1...1.0.2
GUS-W-9950528.
=> Update buildpack.toml to sf-fx-runtime-java to 1.0.2

buildpacks/jvm-function-invoker/CHANGELOG.md, buildpacks/jvm-function-invoker/buildpack.toml
https://github.com/forcedotcom/sf-fx-runtime-java/pull/167
GUS-W-9944570
=> Update SFDC API to v53

buildpacks/jvm-function-invoker/CHANGELOG.md, buildpacks/jvm-function-invoker/buildpack.toml
Update sf-fx-runtime-java to 1.0.4.
=> Update sf-fx-runtime-java to 1.0.4

buildpacks/maven/CHANGELOG.md, buildpacks/maven/lib/dependencies.sh
=> Detect transitive Spring Boot dependency

buildpacks/jvm/CHANGELOG.md, buildpacks/jvm/bin/build
=> Fix .jdk-overlay feature

buildpacks/jvm-function-invoker/CHANGELOG.md, buildpacks/jvm-function-invoker/buildpack.toml
Update sf-fx-runtime-java to 1.0.7
=> Update sf-fx-runtime-java to 1.0.7

buildpacks/jvm/CHANGELOG.md, buildpacks/jvm/src/version.rs, buildpacks/jvm/tests/integration_tests.rs
=> Add OpenJDK August 2022 PSU's

meta-buildpacks/java/CHANGELOG.md, meta-buildpacks/java/buildpack.toml, meta-buildpacks/java/package.toml, test/meta-buildpacks/java/buildpack.toml, test/meta-buildpacks/java/package.toml
https://github.com/heroku/procfile-cnb/releases/tag/v2.0.0
https://github.com/heroku/procfile-cnb/compare/v1.0.2...v2.0.0
GUS-W-11816969.
=> Upgrade heroku/procfile to v2.0.0

buildpacks/jvm/CHANGELOG.md, buildpacks/jvm/src/version.rs, buildpacks/jvm/tests/integration_tests.rs
=> Update default OpenJDK versions for Q2 2023 releases

buildpacks/sbt/buildpack.toml
=> Update sbt buildpack version

.github/workflows/prepare-release.yml, .github/workflows/release-new.yml
Related:
* https://github.com/heroku/languages-github-actions/pull/20
* https://github.com/heroku/languages-github-actions/pull/18
=> Adding release workflow automation

buildpacks/jvm/CHANGELOG.md, buildpacks/jvm/src/version.rs, buildpacks/jvm/tests/integration/versions.rs
=> Update default OpenJDK versions for Q3 2023 releases

buildpacks/jvm-function-invoker/buildpack.toml, buildpacks/jvm/buildpack.toml, buildpacks/maven/buildpack.toml, buildpacks/sbt/buildpack.toml, meta-buildpacks/java-function/buildpack.toml, meta-buildpacks/java/buildpack.toml, meta-buildpacks/scala/buildpack.toml
Related to heroku/languages-github-actions#88
=> Rename CNB release metadata

buildpacks/jvm/CHANGELOG.md, buildpacks/jvm/src/version.rs
Add support for Java 21.
Ref: GUS-W-14144448
=> Add support for Java 21

buildpacks/jvm/CHANGELOG.md, buildpacks/jvm/src/version.rs, buildpacks/jvm/tests/integration/versions.rs
Ref: [GUS-W-14327555](https://gus.my.salesforce.com/a07EE00001ckaNxYAI)
=> Upgrade default JDKs to 21.0.1, 17.0.9, 11.0.21 and 8u392

buildpacks/jvm-function-invoker/CHANGELOG.md, buildpacks/jvm-function-invoker/buildpack.toml
[W-13579117](https://gus.lightning.force.com/a07EE00001TdTe7YAF)
=> Update Java functions runtime to 1.1.5

buildpacks/jvm-function-invoker/CHANGELOG.md, buildpacks/jvm-function-invoker/buildpack.toml
[W-13579117](https://gus.lightning.force.com/a07EE00001TdTe7YAF)
=> Update Java functions runtime to 1.1.6

buildpacks/jvm/CHANGELOG.md, buildpacks/jvm/src/version.rs, buildpacks/jvm/tests/integration/versions.rs
=> Update OpenJDK default versions for Q1 2024

SECURITY.md
This adds the [Salesforce standard OSS SECURITY.md](https://github.com/salesforce/oss-template/blob/main/SECURITY.md).
=> Add Salesforce standard OSS SECURITY.md

buildpacks/jvm/CHANGELOG.md, buildpacks/jvm/src/version.rs, buildpacks/jvm/tests/integration/versions.rs
=> Update OpenJDK default versions for Q2 2024

buildpacks/gradle/CHANGELOG.md, buildpacks/jvm-function-invoker/CHANGELOG.md, buildpacks/jvm/CHANGELOG.md, buildpacks/maven/CHANGELOG.md, buildpacks/sbt/CHANGELOG.md, meta-buildpacks/java-function/CHANGELOG.md, meta-buildpacks/java/CHANGELOG.md, meta-buildpacks/scala/CHANGELOG.md
Adds missing headers, streamlines list character and adds missing version links.
Fixes #595
=> CHANGELOG fixes

buildpacks/jvm/CHANGELOG.md, buildpacks/jvm/openjdk_inventory.toml, buildpacks/jvm/test-apps/java-23-app/system.properties, buildpacks/jvm/test-apps/java-24-app/system.properties, buildpacks/jvm/tests/integration/versions.rs
=> Add support for OpenJDK 24
