heroku/buildpacks-jvm

.circleci/config.yml
meta-buildpacks/java/buildpack.toml
meta-buildpacks/java/package.toml

Updates all buildpack versions used by `heroku/java`. Many of them used an illegal schema `x.y` instead of `x.y.z`.
Skipping changelog since there hasn't been a release yet.

Update buildpack versions

---

.github/workflows/release.yml
buildpacks/jvm/buildpack.toml
meta-buildpacks/java/buildpack.toml

This is a new release workflow that supports mono repositories and automates many steps. Previously, CNB registry releases were triggered by creating a release on GitHub. This had the main issue that the workflow would've required a way to determine which buildpack was supposed to release. It could have been solved by naming conventions, leaving a lot of room for human error.
This new workflow must be manually triggered (in the `Actions` tab) for a specific buildpack in the repo. It will look for the buildpack in the repo and then:
1. Package the buildpack with `pack`
2. Pushes the packaged image to a container registry. (Must be configured in [buildpack metadata](https://github.com/heroku/buildpacks-jvm/blob/dae3392e83c67c14a2f6467344306f8df5d23c1e/meta-buildpacks/java/buildpack.toml#L32- …

Add new release workflow

---

.github/workflows/release.yml
shimmed-buildpacks/clojure/CHANGELOG.md
shimmed-buildpacks/clojure/README.md
shimmed-buildpacks/clojure/buildpack.toml
shimmed-buildpacks/clojure/package.toml
shimmed-buildpacks/gradle/CHANGELOG.md
shimmed-buildpacks/gradle/README.md
shimmed-buildpacks/gradle/buildpack.toml
shimmed-buildpacks/gradle/package.toml
shimmed-buildpacks/scala/CHANGELOG.md
shimmed-buildpacks/scala/README.md
shimmed-buildpacks/scala/buildpack.toml
shimmed-buildpacks/scala/package.toml

Adds support for shimmed V2 buildpacks. The main motivator behind this is that we ideally want to keep track of all JVM CNBs in one place. Since we won't have native CNBs for Scala/Clojure soon, we need a way to track shimmed releases somewhere.
Each shimmed CNB has its own directory containing:
- A `README.md` explaining that this buildpack is shimmed
- A `CHANGELOG.md` which entries point to the V2 CHANGELOG
- A `buildpack.toml` with special metadata that references a specific V2 buildpack release tarball. As normal, it also contains a CNB version number. Since this file is checked in, we can track CNB releases of shimmed buildpacks and have a way to control their CNB version numbers.
- A `package.toml`
By itself, this directory is not a valid CNB. However, during the regular release …

Shimmed Buildpacks

---

.github/scripts/release-workflow-package-push.sh

#11 broke the release workflow for non-shimmed buildpacks by accident.
`jq` with  `-r` will output `null` for values that couldn't be found. The script later checks for an empty string which, of course, will never fail and trigger the shim release path. By using `jq`'s alternative operator `//`, `null` values will now default to an empty string where it matters.

Fix release workflow

---

.github/scripts/release-workflow-package-push.sh
.github/scripts/release-workflow-prepare-pr.sh
.github/workflows/release.yml
buildpacks/jvm/CHANGELOG.md
buildpacks/jvm/buildpack.toml
buildpacks/maven/CHANGELOG.md
buildpacks/maven/buildpack.toml
meta-buildpacks/java/CHANGELOG.md
meta-buildpacks/java/buildpack.toml
shimmed-buildpacks/clojure/CHANGELOG.md
shimmed-buildpacks/gradle/CHANGELOG.md
shimmed-buildpacks/scala/CHANGELOG.md

Enhances the release workflow to automatically open a PR after a release that:
1. Bumps the version number of the released buildpack
2. Move items from `Unreleased` to the released version number in `CHANGELOG.md` for the released buildpack
3. Updates meta-buildpacks that use the released buildpack to use the next unreleased version
4. Update meta-buildpacks `CHANGELOG.md` to include the version bump of its dependencies
Also updates all CHANGELOGs to adhere to [Keep a Changelog](https://keepachangelog.com/en/1.0.0/).

Add automated post-release PRs workflow

---

buildpacks/jvm-function-invoker/CHANGELOG.md
buildpacks/jvm-function-invoker/bin/build
buildpacks/jvm-function-invoker/bin/detect
buildpacks/jvm-function-invoker/buildpack.toml
common/lib/jvm_buildpack_utils.sh
common/lib/log/cnb.sh
common/meta-build.sh
common/rsync-build.sh
common/shim-build.sh
meta-buildpacks/java-function/CHANGELOG.md
meta-buildpacks/java-function/buildpack.toml

From the changelog:
* Function runtime binary URL no longer has to be specified with the `JVM_INVOKER_JAR_URL` environment variable.
* Functions are now detected during build. This means the build will now fail if more or less than one valid
Salesforce Java function is detected in the project.
* The Java function runtime binary integrity is now checked after download
* Java function runtime is now cached between builds

Java Function Invoker 0.2.0

---

buildpacks/jvm-function-invoker/buildpack.toml

Since the function buildpack wasn't released yet there is no changelog and/or version bump necessary.

Update function runtime checksum

---

buildpacks/jvm-function-invoker/CHANGELOG.md
buildpacks/jvm-function-invoker/bin/build
buildpacks/jvm-function-invoker/bin/detect
buildpacks/maven/CHANGELOG.md
buildpacks/maven/bin/detect

Removes the checksum verification for invoker/runtime downloads. The runtime is not yet stable and there will be many updates in s short period of time. To ease testing those changes, the checksum check had to go. It will be re-enabled as soon as the runtime spec settled.
Also introduces a new `[requires]`/`[provides]` pair: `jvm-application`. The Maven buildpack will provide (and require) it. Downstream buildpacks can use this to require a built JVM application - regardless of the build tooling used. This was a requirement for the function invoker buildpack.

jvm-function-invoker 0.2.1

---

.circleci/config.yml
.github/scripts/release-workflow-package-push.sh
.github/scripts/release-workflow-prepare-pr.sh
.github/workflows/release.yml
meta-buildpacks/java-function/CHANGELOG.md
meta-buildpacks/java-function/build.sh
meta-buildpacks/java-function/buildpack.toml
meta-buildpacks/java-function/package.toml
meta-buildpacks/java/CHANGELOG.md
meta-buildpacks/java/build.sh
meta-buildpacks/java/buildpack.toml
meta-buildpacks/java/package.toml
test/meta-buildpacks/java-function/build.sh
test/meta-buildpacks/java-function/buildpack.toml
test/meta-buildpacks/java-function/package.toml
test/meta-buildpacks/java/build.sh
test/meta-buildpacks/java/buildpack.toml
test/meta-buildpacks/java/package.toml
test/specs/java/spec_helper.rb

Meta Buildpacks now reference released Docker images for their dependencies instead of local directory paths. This ensures that meta buildpacks contain the same code as the standalone buildpacks.
For testing, a new set of meta buildpacks have been created to test the combination of all changes in the repository across all buildpacks. These still reference local directory paths.

Make meta buildpacks reference released version images

---

.github/scripts/release-workflow-package-push.sh
.github/workflows/release.yml

Addendum to #33 
CNB tooling does not work when image names are prefixed with docker://. This removes the prefix for most of the release process and just adds it to the argument of the PR script.

Remove docker:// prefix in release process

---

.github/scripts/release-workflow-package-push.sh
.github/scripts/release-workflow-prepare-pr.sh
.github/workflows/release.yml
meta-buildpacks/java-function/CHANGELOG.md
meta-buildpacks/java-function/package.toml
meta-buildpacks/java/CHANGELOG.md
meta-buildpacks/java/package.toml

Another (and hopefully the last) addendum to fix the release process after #33. This changes the image references to use digests. This is more strict and is in-line with what CNB release tooling expects.
See: #34 #33

Use Docker image digests in meta buildpacks

---

buildpacks/jvm-function-invoker/CHANGELOG.md
buildpacks/jvm-function-invoker/bin/build
buildpacks/jvm/CHANGELOG.md
buildpacks/jvm/bin/build
buildpacks/jvm/lib/v3/common.sh

These buildpacks run with a slightly older version of `pack`, causing some incompatibilities. This PR adds workarounds/fixes for those. In addition:
- `heroku/jvm` logging now bolds status lines (now consistent with other buildpacks)
- `heroku/jvm-function-invoker` now supports setting `PORT`

Java functions fixes

---

buildpacks/jvm-function-invoker/buildpack.toml
buildpacks/jvm/buildpack.toml
buildpacks/maven/buildpack.toml
meta-buildpacks/java-function/buildpack.toml
meta-buildpacks/java/buildpack.toml
shimmed-buildpacks/clojure/buildpack.toml
shimmed-buildpacks/gradle/buildpack.toml
shimmed-buildpacks/scala/buildpack.toml

In anticipation of GA for the official Cloud Native Buildpack registry, this PR adds missing metadata to the buildpacks in this repository.
Closes [W-8925222](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B00000097HLvIAM/view)

Add buildpack metadata

---

buildpacks/maven/CHANGELOG.md
buildpacks/maven/README.md

Adds documentation to `heroku/maven`'s README file. [Rendered README.md](https://github.com/heroku/buildpacks-jvm/blob/ff1a53bc38d5dc588453995240042390e0b72835/buildpacks/maven/README.md).
Closes [W-8961226](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B0000008wyvOIAQ/view)

Add heroku/maven README

---

buildpacks/jvm-function-invoker/CHANGELOG.md
buildpacks/jvm-function-invoker/bin/build
buildpacks/jvm-function-invoker/buildpack.toml

This change also re-enables integrity checking of the downloaded runtime binary.

Update Java function runtime to 0.1.1-ea

---

buildpacks/jvm-function-invoker/CHANGELOG.md
buildpacks/jvm-function-invoker/bin/build
buildpacks/jvm-function-invoker/opt/run.sh

Add support for the `SF_FX_REMOTE_DEBUG` runtime environment variable. If set, the invoker will listen for incoming JDWP  connections on port `5005`, allowing customers to remotely attach a debugger to debug their function.
Closes [W-9207077](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07AH000000KbXWYA0/view)

Add support for SF_FX_REMOTE_DEBUG

---

buildpacks/maven/CHANGELOG.md
buildpacks/maven/bin/build

Allows subsequent buildpacks to use installed Maven when they depend on `M2_HOME` being set.
References [W-9041788](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07AH0000008sWEYAY/view)
Closes [W-9155483](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07AH000000BDqCYAW/view)

Set M2_HOME for subsequent buildpacks

---

buildpacks/jvm/bin/detect

The JVM buildpack currently is using an old Buildpack API with the Build Plan:
```
===> DETECTING
Warning: Warning: buildpack heroku/jvm has a "version" key. This key is deprecated in build plan requirements in buildpack API 0.3. "metadata.version" should be used instead
```
This PR fixes this and uses the new format.

remove warning in jvm buildpack, deprecation of version field

---

buildpacks/jvm-function-invoker/CHANGELOG.md
buildpacks/jvm-function-invoker/buildpack.toml
test/meta-buildpacks/java-function/buildpack.toml

Also bumps version to `0.3.0` to indicate the first version of the buildpack after the switch to Rust as the implementation language.
References [GUS-W-9562648](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07AH000000QSSpYAO/view)

Update JVM function runtime to 1.0.0

---

buildpacks/maven/CHANGELOG.md
buildpacks/maven/buildpack.toml

This allows any linux distro to use the maven CNB since it isn't platform specific. The any stack stack id is [supported starting in buildpack API `0.5`](https://github.com/buildpacks/spec/issues/140), so I bumped that.

support for any linux stack 

---

buildpacks/jvm/CHANGELOG.md
buildpacks/jvm/lib/jvm.sh

Update OpenJDK for Java 16 to 16.0.2

---

buildpacks/jvm-function-invoker/CHANGELOG.md
buildpacks/jvm-function-invoker/buildpack.toml
test/meta-buildpacks/java-function/buildpack.toml

Same as #113 but for the bash version of the buildpack after we reverted back to it in #123. Also bumps the buildpack version to `0.4.0` to better indicate this major change compared to it being released as`0.3.1`.

Update JVM function runtime to 1.0.0 

---

buildpacks/jvm-function-invoker/buildpack.toml
buildpacks/jvm/buildpack.toml
buildpacks/maven/buildpack.toml
meta-buildpacks/java-function/buildpack.toml
meta-buildpacks/java-function/package.toml
meta-buildpacks/java/buildpack.toml
meta-buildpacks/java/package.toml
shimmed-buildpacks/clojure/buildpack.toml
shimmed-buildpacks/gradle/buildpack.toml
shimmed-buildpacks/scala/buildpack.toml

The ECR registry to which we publish our images has a custom alias of `heroku-buildpacks` that can be used in place of the raw registry name.
The Node.js CNBs have been using this for some time.
Fixes GUS-W-9672346.

Switch ECR registry URLs to use custom registry alias

---

.github/scripts/release-workflow-package-push.sh

Previously if duplicate buildpack IDs existed in the repository, the publish script would publish the first buildpack found, and exit 0.
Whilst Java currently doesn't have duplicate buildpack IDs (since the test buildpacks have a `-test` suffix), the Node.js ones do, leading to the test buildpacks being published instead of the intended buildpack.
With this change, the publish script now traverses the repository and errors if more than one buildpack with the same ID was found.
In addition, I've added a bit more logging around the name/path/version of the found buildpack, which would have aided debugging the Node.js issue.
I'll be making these same changes (and also fixing the test buildpack names) in the Node.js repo shortly.
Refs GUS-W-9672962.

Make publishing script fail if duplicate buildpack IDs found

---

.github/dependabot.yml

See:
https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/about-dependabot-version-updates#supported-repositories-and-ecosystems
Whilst this repository isn't using Rust right now, it will be shortly, so I've enabled Cargo updates now to save churn.
I've also changed the frequency to daily, so we don't have to wait as long.
Refs GUS-W-9678950.

Enable Dependabot for GitHub Actions and Cargo

---

buildpacks/maven/CHANGELOG.md
buildpacks/maven/bin/build
test/specs/maven/misc_spec.rb

If a developer has accidentally changed the permissions on their `mvnw` executable they should be able to deploy.
GUS-W-9689448

Ensure the user-provided mvnw wrapper script is executable

---

.github/dependabot.yml

Since Dependabot is looking in the repo root, and that only works if either the crate exists there, or the repo is using [cargo workspaces](https://doc.rust-lang.org/cargo/reference/workspaces.html) with a suitably configured repo root `Cargo.toml`.
Until this repo uses cargo workspaces (and the build scripts are adapted to work with workspaces), the Dependabot config needs to reference each crate path explicitly.
Fixes the error seen here:
https://github.com/heroku/buildpacks-jvm/network/updates/191049380
GUS-W-9839985.

Fix Dependabot configuration for Cargo

---

.circleci/config.yml

Most of the CI jobs are installing Rust stable themselves (so are already using Rust 1.55), however this one is using `cimg/rust` (causing the rustup install script to not update major version), so needs updating explicitly.
Refactoring the CI jobs to use the optimal combination of images/install steps will happen in later PRs (it's more involved since it requires splitting the build and cutlass steps out, so we don't need to use the `machine` executor etc).
The image tag has intentionally been switched to the `1.NN` alias rather than `1.NN.N`, to reduce CI config churn for patch releases, and consistency with the other Rust repos.
Release notes:
https://blog.rust-lang.org/2021/07/29/Rust-1.54.0.html
https://blog.rust-lang.org/2021/09/09/Rust-1.55.0.html
GUS-W-9885998.

Update CI to Rust 1.55

---

buildpacks/jvm-function-invoker/src/build.rs
buildpacks/jvm-function-invoker/src/detect.rs
buildpacks/jvm-function-invoker/src/main.rs

Clippy has a `pedantic` lint category for lints that are more opinionated, or that sometimes have a higher false positive rate.
Many of these lints are actually very useful (particularly for those new to Rust, like we are), and so we should take advantage of them - with the understanding that it's absolutely fine to disable individual pedantic lints in the future that we find annoying/counter-productive.
The list of all Clippy lints by category can be found here:
https://rust-lang.github.io/rust-clippy/stable/index.html
In addition, the `unused_crate_dependencies` lint has been enabled to ensure the crate doesn't have unused dependencies:
https://doc.rust-lang.org/rustc/lints/listing/allowed-by-default.html#unused-crate-dependencies
This is a port of: …

function-invoker: Enable `clippy::pedantic` and `unused_crate_dependencies` lints

---

buildpacks/jvm-function-invoker/CHANGELOG.md
buildpacks/jvm-function-invoker/Cargo.lock
buildpacks/jvm-function-invoker/Cargo.toml
buildpacks/jvm-function-invoker/buildpack.toml

Since they are major version updates (that don't get picked up automatically by the tilde dependency version ranges), both packages have to be updated simultaneously (which Dependabot can't do), due to:
https://github.com/Malax/libcnb.rs/issues/90
Changes:
https://github.com/Malax/libcnb.rs/compare/v0.2.0...v0.3.0
https://github.com/heroku/libherokubuildpack/compare/v0.2.0...v0.3.0
The buildpack's API version also had to be bumped due to:
https://github.com/Malax/libcnb.rs/pull/50
The changes in buildpack API 0.5 are:
https://github.com/buildpacks/spec/releases/tag/buildpack%2Fv0.5
Closes #162.
Closes #163.
GUS-W-9921906.

JVM invoker: Update libcnb and libherokubuildpack to 0.3.0

---

.github/scripts/release-workflow-package-push.sh
.github/scripts/release-workflow-prepare-pr.sh

Currently if you attempt to release a buildpack with id `heroku/java   ` (with whitespace before or after) it will fail. It also takes a few minutes to fail and isn't 100% obvious in the message that the failure is due to whitespace.
This trims whitespace from the input on both release scripts. I also modified the error message to quote the variable so if it's used in the future without being trimmed first, the error would be easier to detect.
https://github.com/heroku/buildpacks-nodejs/pull/132

Ignore whitespace in release script

---

LICENSE
README.md
buildpacks/jvm-function-invoker/CHANGELOG.md
buildpacks/jvm-function-invoker/README.md
buildpacks/jvm-function-invoker/buildpack.toml
buildpacks/jvm/CHANGELOG.md
buildpacks/jvm/README.md
buildpacks/jvm/buildpack.toml
buildpacks/maven/CHANGELOG.md
buildpacks/maven/README.md
buildpacks/maven/buildpack.toml
meta-buildpacks/java-function/CHANGELOG.md
meta-buildpacks/java-function/buildpack.toml
meta-buildpacks/java/CHANGELOG.md
meta-buildpacks/java/README.md
meta-buildpacks/java/buildpack.toml
shimmed-buildpacks/clojure/CHANGELOG.md
shimmed-buildpacks/clojure/buildpack.toml
shimmed-buildpacks/gradle/CHANGELOG.md
shimmed-buildpacks/gradle/buildpack.toml
shimmed-buildpacks/scala/CHANGELOG.md
shimmed-buildpacks/scala/buildpack.toml

Since:
- it's the license Salesforce prefers that we use for open source projects:
https://github.com/salesforce/oss-template/blob/master/license_info.md
- it's what some of our other newer repositories are already using, and it would be great to be consistent
- it's not that different from MIT:
https://fossa.com/blog/open-source-software-licenses-101-bsd-3-clause-license/
All contributors to this repository so far are Salesforce employees, so there are no external code contributors from whom we need to ask permission before changing the license type.
GUS-W-10140085.

Switch to BSD 3-Clause License

---

.circleci/config.yml

https://blog.rust-lang.org/2021/12/02/Rust-1.57.0.html
GUS-W-10261473.

Update to Rust 1.57 in CI

---

.circleci/config.yml

Changes:
https://github.com/buildpacks/pack/releases/tag/v0.23.0
https://github.com/buildpacks/pack-orb/releases/tag/0.2.3
https://github.com/buildpacks/pack-orb/releases/tag/0.2.4
The Pack version bump for the GitHub actions release workflow needs a new release of `buildpacks/github-actions`, after which Dependabot will open a PR. This PR just handles CI (which is good to update first, given the release scripts don't have tests).
GUS-W-10301655.

Update Pack to v0.23.0 in CI

---

shimmed-buildpacks/gradle/CHANGELOG.md
shimmed-buildpacks/gradle/buildpack.toml

To match `heroku/maven`, supported stacks have been changed to `*` in addition to the update to v36.

Update heroku/gradle to v36

---

.github/scripts/release-workflow-package-push.sh
.github/workflows/release.yml

Yet another attempt to fix the packaging to `.cnb` files during release. We need to write to `$TMPDIR` as the project directory will be `git reset --hard`, removing the packaged file.

Fix CNB package file upload

---

buildpacks/jvm-function-invoker/buildpack.toml
buildpacks/jvm/buildpack.toml
buildpacks/maven/buildpack.toml
meta-buildpacks/java-function/buildpack.toml
meta-buildpacks/java/buildpack.toml
shimmed-buildpacks/clojure/buildpack.toml
shimmed-buildpacks/gradle/buildpack.toml
shimmed-buildpacks/scala/buildpack.toml

@edmorley pointed out to me that the licenses table is wrong for JVM buildpacks. This PR fixes the issue.

Fix licenses table in buildpack.toml files

---

.github/scripts/release-workflow-package-push.sh
.github/workflows/release.yml

Fixing https://github.com/heroku/buildpacks-jvm/pull/215#issuecomment-991054661 and other issues (see: #224, #225, #226) in the release action. Successful release run from the code in this branch can be seen here: https://github.com/heroku/buildpacks-jvm/actions/runs/1657597150
Closes GUS-W-10383141

Install libcnb-cargo instead of cargo-make when releasing

---

.circleci/config.yml

https://blog.rust-lang.org/2022/01/13/Rust-1.58.0.html
GUS-W-10435310

Update to Rust 1.58 in CI

---

buildpacks/jvm-function-invoker/CHANGELOG.md
buildpacks/jvm-function-invoker/Cargo.lock
buildpacks/jvm-function-invoker/Cargo.toml
buildpacks/jvm-function-invoker/src/layers/bundle.rs
buildpacks/jvm-function-invoker/src/layers/runtime.rs
buildpacks/jvm-function-invoker/src/main.rs

Opening a separate PR to #236, since we have to update both the `libcnb` and `libherokubuildpack` packages at the same time, so can't use the Dependabot PRs for those.
libcnb changes:
https://github.com/Malax/libcnb.rs/blob/main/libcnb/CHANGELOG.md#050-2022-01-14
libherokubuildpack changes:
https://github.com/heroku/libherokubuildpack/compare/v0.4.0...v0.5.0
I also removed and recreated `Cargo.lock` to pick up stray transitive dependency updates.
GUS-W-10435655.

Migrate to libcnb and libherokubuildpack 0.5.0

---

buildpacks/jvm-function-invoker/src/main.rs

Removes usages of `use libcnb::Error` to avoid ambiguity over which `Error` is being used in function signatures - similar to Malax/libcnb.rs#192.
Also cleans up a few use statements.

Always reference `libcnb::Error` by its full path

---

shimmed-buildpacks/scala/CHANGELOG.md
shimmed-buildpacks/scala/buildpack.toml

Update shimmed buildpack to most recent upstream version.
References: GUS-W-10666714

Update heroku/scala to v92

---

buildpacks/jvm/buildpack.toml
test/meta-buildpacks/java-function/buildpack.toml
test/meta-buildpacks/java/buildpack.toml

Due to a failed release, we need to bump to the version to try again (the release [failed due to a timeout issue](https://github.com/heroku/buildpacks-jvm/runs/5391442046?check_suite_focus=true)). `0.1.13` will be yanked.

Bump heroku/jvm to 0.1.14

---

test/specs/maven/customization_spec.rb

After spending some time trying to figure out why this test is failing on CI, I decided to temporarily
disable it to unblock CI. Re-enabling this test should be done ASAP.

Disable Maven dependency list cutlass test

---

.circleci/config.yml

There have been a few updates we should pick up (https://github.com/buildpacks/pack/releases/tag/v0.24.0, https://github.com/buildpacks/pack/releases/tag/v0.24.1).
GUS-W-10708989.
GUS-W-11136285.

Bump to pack 0.26.0

---

.github/workflows/release.yml

Since `PUBLIC_REPO_TOKEN` doesn't mention GitHub, and the "repo" part of the name could also be relating to Docker Hub or ECR repositories.
I've not used the name `GITHUB_TOKEN`, since for GitHub Actions there is already an env var of that name provided automatically. That env var isn't suitable for publishing CNB releases, since we need to open an issue against the upstream CNB registry's index repo to trigger a release, whereas the GH Actions provided token only gives access to the repository where the action ran.
GUS-W-11031533.

Rename `PUBLIC_REPO_TOKEN` to `CNB_REGISTRY_RELEASE_BOT_GITHUB_TOKEN`

---

.github/dependabot.yml
.github/workflows/check_changelog.yml

By default Dependabot sets `dependencies` and `<lang>` labels on PRs it opens. However previously those were overridden by the manual `labels` setting here.
This is inconsistent with how we have other repos configured, and means I can't as easily exclude Dependabot PRs from the PR review reminders GitHub feature that I'm about to enable.

Make Dependabot labels consistent with other repos

---

.circleci/config.yml
Cargo.lock
buildpacks/jvm-function-invoker/Cargo.toml
buildpacks/jvm/Cargo.toml
buildpacks/maven/Cargo.toml

Since merging all open dependabot PRs would take a lot of time with the required CI after each of them, this PR bundles these version bumps in one.

Bump Cargo dependencies

---

buildpacks/jvm-function-invoker/CHANGELOG.md
buildpacks/jvm-function-invoker/buildpack.toml
buildpacks/jvm/CHANGELOG.md
buildpacks/jvm/buildpack.toml
buildpacks/jvm/src/main.rs
buildpacks/jvm/src/version.rs
buildpacks/maven/CHANGELOG.md
buildpacks/maven/buildpack.toml

Adds `heroku-22` support for all native CNB buildpacks. Shimmed buildpacks will follow when the classic buildpack support for `heroku-22` is completed.
Starting with `heroku-22`, [Azul Zulu Builds of OpenJDK](https://www.azul.com/downloads/?package=jdk#download-openjdk) is now the default OpenJDK distribution. `heroku/jvm` has been modified accordingly.
Closes GUS-W-10343951

Add heroku-22 support

---

buildpacks/jvm/CHANGELOG.md
buildpacks/jvm/src/version.rs
buildpacks/maven/CHANGELOG.md
buildpacks/maven/buildpack.toml

Whilst the global S3 endpoint (`s3.amazonaws.com`) still works, AWS now recommends using the appropriate regional endpoint to access the bucket:
https://docs.aws.amazon.com/AmazonS3/latest/userguide/VirtualHosting.html#s3-legacy-endpoints
Our buildpack buckets are in `us-east-1`, whose regional domain is `*.s3.us-east-1.amazonaws.com`:
https://docs.aws.amazon.com/general/latest/gr/s3.html#s3_region
GUS-W-11283397.

Switch to the recommended regional S3 domain

---

buildpacks/jvm-function-invoker/README.md
buildpacks/jvm/CHANGELOG.md
buildpacks/maven/CHANGELOG.md

libcnb.rs moved from:
https://github.com/Malax/libcnb.rs
...to:
https://github.com/heroku/libcnb.rs
GUS-W-11312893.

Update libcnb.rs URLs for migration to the heroku org

---

Cargo.lock
buildpacks/jvm-function-invoker/CHANGELOG.md
buildpacks/jvm-function-invoker/Cargo.toml
buildpacks/jvm-function-invoker/src/error.rs
buildpacks/jvm-function-invoker/src/main.rs
buildpacks/jvm/CHANGELOG.md
buildpacks/jvm/Cargo.toml
buildpacks/jvm/src/errors.rs
buildpacks/jvm/src/main.rs
buildpacks/jvm/tests/integration_tests.rs
buildpacks/maven/CHANGELOG.md
buildpacks/maven/Cargo.toml
buildpacks/maven/src/errors.rs
buildpacks/maven/src/main.rs

Updates this buildpack to `libcnb` `0.8.0` and `libcnb-test` `0.4.0`. Some minor code changes were required due to breaking changes. 
Closes GUS-W-11342158

Upgrade to libcnb 0.8.0

---

buildpacks/jvm-function-invoker/CHANGELOG.md
buildpacks/jvm-function-invoker/buildpack.toml
meta-buildpacks/java-function/CHANGELOG.md
meta-buildpacks/java-function/buildpack.toml
meta-buildpacks/java-function/package.toml
test/meta-buildpacks/java-function/buildpack.toml

Manually made the post release update for `heroku/jvm-function-invoker 0.6.3`
Update buildpack versions and changelogs

Post-release updates: heroku/jvm-function-invoker 0.6.3

---

meta-buildpacks/java/CHANGELOG.md
meta-buildpacks/java/buildpack.toml

Pull-request to update buildpack versions and changelogs
after releasing version `0.6.1` of `heroku/java`.
https://github.com/buildpacks/registry-index/issues/3404

Post-release updates: heroku/java 0.6.1

---

.circleci/config.yml
buildpacks/jvm/tests/integration_tests.rs
buildpacks/maven/tests/customization_tests.rs
buildpacks/maven/tests/misc_tests.rs
buildpacks/maven/tests/polyglot_tests.rs
buildpacks/maven/tests/process_types_tests.rs
buildpacks/maven/tests/settings_xml_tests.rs
buildpacks/maven/tests/version_handling_tests.rs
test/specs/java-function/spec_helper.rb
test/specs/java/spec_helper.rb

This PR changes the existing integration tests to use an environment variable instead of a hardcoded value to determine the builder used during testing. This allows us to set up a test matrix in CI that ensures we test all supported builders/stacks. This is also implemented in this PR.
Closes GUS-W-11300244

Test multiple builders/stacks in integration tests

---

Cargo.lock
buildpacks/jvm-function-invoker/CHANGELOG.md
buildpacks/jvm-function-invoker/Cargo.toml
buildpacks/jvm-function-invoker/buildpack.toml
buildpacks/jvm-function-invoker/src/main.rs
buildpacks/jvm/CHANGELOG.md
buildpacks/jvm/Cargo.toml
buildpacks/jvm/buildpack.toml
buildpacks/maven/CHANGELOG.md
buildpacks/maven/Cargo.toml
buildpacks/maven/buildpack.toml
buildpacks/maven/src/main.rs
meta-buildpacks/java-function/CHANGELOG.md
meta-buildpacks/java-function/buildpack.toml
meta-buildpacks/java/CHANGELOG.md
meta-buildpacks/java/buildpack.toml
test/meta-buildpacks/java-function/buildpack.toml
test/meta-buildpacks/java/buildpack.toml

Update `libcnb` and `libherokubuildpack` to `0.10.0` and therefore to buildpack API `0.8` as well.
Closes GUS-W-11680341

Update libcnb to 0.10.0

---

Cargo.lock
Cargo.toml
buildpacks/jvm-function-invoker/Cargo.toml
buildpacks/jvm-function-invoker/src/common.rs
buildpacks/jvm-function-invoker/src/error.rs
buildpacks/jvm-function-invoker/src/layers/bundle.rs
buildpacks/jvm-function-invoker/src/layers/runtime.rs
buildpacks/jvm-function-invoker/src/main.rs
buildpacks/jvm/Cargo.toml
buildpacks/jvm/src/errors.rs
buildpacks/jvm/src/layers/heroku_metrics_agent.rs
buildpacks/jvm/src/layers/openjdk.rs
buildpacks/jvm/src/main.rs
buildpacks/jvm/src/util.rs
buildpacks/maven/Cargo.toml
buildpacks/maven/src/errors.rs
buildpacks/maven/src/layer/maven.rs
buildpacks/maven/src/main.rs
buildpacks/maven/src/settings.rs
buildpacks/maven/src/warnings.rs

Update libcnb to `0.11.0`, mostly changes to `libherokubuildpack` imports.

Update libcnb to 0.11.0

---

buildpacks/jvm-function-invoker/CHANGELOG.md
buildpacks/jvm-function-invoker/buildpack.toml
buildpacks/maven/CHANGELOG.md

This PR also fixes the libcnb version bump related CHANGELOG entries for buildpacks where they were wrong.

Update JVM function runtime to 1.1.0

---

buildpacks/jvm/CHANGELOG.md
buildpacks/jvm/src/version.rs
buildpacks/jvm/tests/integration_tests.rs

* Default version for **OpenJDK 8** is now `1.8.0_352`.
* Default version for **OpenJDK 11** is now `11.0.17`.
* Default version for **OpenJDK 13** is now `13.0.13`.
* Default version for **OpenJDK 15** is now `15.0.9`.
* Default version for **OpenJDK 17** is now `17.0.5`.
* Default version for **OpenJDK 19** is now `19.0.1`. 
Also updates CHANGELOG to contain the version bumps made by @dependabot
Closes GUS-W-11930880

OpenJDK Q4 2022 updates

---

.github/workflows/release.yml

The release workflow no longer works in its current form. I suspect that the GitHub org changed the default permissions of the token minted for an GitHub action workflow is now read-only: https://github.blog/changelog/2021-04-20-github-actions-control-permissions-for-github_token/
Example of a failed run: https://github.com/heroku/buildpacks-jvm/actions/runs/3287988945 (See: `Resource not accessible by integration`)
This PR adds the required permission back to the `release` job so it can create releases again. It also adds the required permissions for the https://github.com/peter-evans/create-pull-request action we use to create the update PR.
Closes GUS-W-11937667

Add required permissions to release job

---

buildpacks/jvm-function-invoker/buildpack.toml
buildpacks/jvm/CHANGELOG.md
buildpacks/jvm/buildpack.toml
buildpacks/maven/buildpack.toml
meta-buildpacks/java-function/CHANGELOG.md
meta-buildpacks/java-function/buildpack.toml
meta-buildpacks/java-function/package.toml
meta-buildpacks/java/CHANGELOG.md
meta-buildpacks/java/buildpack.toml
meta-buildpacks/java/package.toml
test/meta-buildpacks/java-function/buildpack.toml
test/meta-buildpacks/java/buildpack.toml

Due to a failed workflow (https://github.com/heroku/buildpacks-jvm/actions/runs/3287988945), this is created by hand instead.

Post-release updates: heroku/jvm 1.0.5

---

buildpacks/jvm-function-invoker/CHANGELOG.md
buildpacks/jvm-function-invoker/buildpack.toml

Updates buildpack to use the `1.1.2` version of the Java function invoker

Update sf-fx-runtime-java from 1.1.1 to 1.1.2

---

buildpacks/jvm-function-invoker/src/common.rs
buildpacks/jvm-function-invoker/src/error.rs
buildpacks/jvm-function-invoker/src/layers/bundle.rs
buildpacks/jvm-function-invoker/src/layers/mod.rs
buildpacks/jvm-function-invoker/src/layers/opt.rs
buildpacks/jvm-function-invoker/src/layers/runtime.rs
buildpacks/jvm-function-invoker/src/main.rs
buildpacks/jvm/src/bin/heroku_database_env_var_rewrite.rs
buildpacks/jvm/src/bin/heroku_metrics_agent_setup.rs
buildpacks/jvm/src/constants.rs
buildpacks/jvm/src/errors.rs
buildpacks/jvm/src/layers/heroku_metrics_agent.rs
buildpacks/jvm/src/layers/mod.rs
buildpacks/jvm/src/layers/openjdk.rs
buildpacks/jvm/src/layers/runtime.rs
buildpacks/jvm/src/main.rs
buildpacks/jvm/src/util.rs
buildpacks/jvm/src/version.rs
buildpacks/maven/src/errors.rs
buildpacks/maven/src/framework.rs
buildpacks/maven/src/layer/maven.rs
buildpacks/maven/src/layer/maven_repo.rs
buildpacks/maven/src/layer/mod.rs
buildpacks/maven/src/main.rs
buildpacks/maven/src/mode.rs
buildpacks/maven/src/settings.rs
buildpacks/maven/src/util.rs
buildpacks/maven/src/warnings.rs

This allows clippy to detect i.e. unused variants. Fixes #403.

Use `pub(crate)` instead of `pub` in buildpacks

---

buildpacks/jvm/CHANGELOG.md
buildpacks/jvm/buildpack.toml
meta-buildpacks/java-function/CHANGELOG.md
meta-buildpacks/java-function/buildpack.toml
meta-buildpacks/java-function/package.toml
meta-buildpacks/java/CHANGELOG.md
meta-buildpacks/java/buildpack.toml
meta-buildpacks/java/package.toml
test/meta-buildpacks/java-function/buildpack.toml
test/meta-buildpacks/java/buildpack.toml

Since [the automation failed](https://github.com/heroku/buildpacks-jvm/actions/runs/4499126562/jobs/7920964785), this PR adds the changes by hand.

Post-release updates: heroku/jvm 1.0.7

---

buildpacks/jvm/CHANGELOG.md
buildpacks/jvm/buildpack.toml

Update [Heroku JVM metrics agent](https://github.com/heroku/heroku-java-metrics-agent) to the most recent version, `4.0.1`. This is a backwards compatible version bump.
Ref: GUS-W-12775483

Update Heroku JVM metrics agent to `4.0.1`

---

buildpacks/maven/tests/customization_tests.rs
buildpacks/maven/tests/misc_tests.rs
test-fixtures/simple-http-service/pom.xml
test-fixtures/simple-http-service/system.properties

The currently used undertow version we use in one of the test fixtures has a security vulnerability. This shouldn't cause problems for the buildpack and its users, but out of an abundance of caution and to make security scanner notifications go away, this PR bumps the undertow version.
Closes GUS-W-12775352

Bump undertow-core version in tests to silence security scanners

---

Cargo.lock
Cargo.toml
buildpacks-jvm-shared/Cargo.toml
buildpacks-jvm-shared/src/lib.rs
buildpacks/jvm-function-invoker/Cargo.toml
buildpacks/jvm/Cargo.toml
buildpacks/jvm/src/errors.rs
buildpacks/jvm/src/main.rs
buildpacks/maven/Cargo.toml
buildpacks/maven/src/errors.rs
buildpacks/maven/src/main.rs

- Introduce a shared crate for common code between JVM buildpacks
- Moves duplicated `log_please_try_again_error` function to shared crate
- Rename crates to use a consistent naming scheme (this has no effect to the users as they only use the buildpack IDs which don't change)
Ref: GUS-W-13035981

Add crate for common code between JVM buildpacks

---

Cargo.lock
Cargo.toml
buildpacks/jvm-function-invoker/CHANGELOG.md
buildpacks/jvm-function-invoker/buildpack.toml
buildpacks/jvm-function-invoker/src/main.rs
buildpacks/jvm/CHANGELOG.md
buildpacks/jvm/buildpack.toml
buildpacks/maven/CHANGELOG.md
buildpacks/maven/buildpack.toml
buildpacks/maven/src/framework.rs
buildpacks/sbt/buildpack.toml
buildpacks/sbt/src/build_configuration.rs
buildpacks/sbt/src/errors.rs

(applies to all released buildpacks)
* Upgrade `libcnb` and `libherokubuildpack` to `0.12.0`. ([#463](https://github.com/heroku/buildpacks-jvm/pull/463))
* The buildpack now implements Buildpack API 0.9 instead of 0.8, and so requires `lifecycle` 0.15.x or newer. ([#463](https://github.com/heroku/buildpacks-jvm/pull/463))

Update to libcnb `0.12.0` and buildpack API `0.9`

---

buildpacks/sbt/assets/heroku_buildpack_plugin_sbt_v1.scala
buildpacks/sbt/tests/integration_tests.rs

sbt will output the following when run in batch mode:
> Executing in batch mode. For better performance use sbt's shell
This might be confusing to users of the buildpack and is not an actionable warning for them. This PR disables that warning for sbt 1.x projects.
https://www.scala-sbt.org/1.x/docs/Running.html#Batch+mode

Suppress batch mode warning for sbt `1.x`

---

buildpacks/maven/src/framework.rs
buildpacks/maven/src/util.rs

Use `list_directory_contents` from shared crate instead of duplicated local version in `heroku/maven`.

Use `list_directory_contents` from shared crate

---

.github/workflows/release.yml
buildpacks/jvm-function-invoker/buildpack.toml
buildpacks/jvm/buildpack.toml
buildpacks/maven/buildpack.toml
buildpacks/sbt/buildpack.toml
meta-buildpacks/java-function/buildpack.toml
meta-buildpacks/java/buildpack.toml
meta-buildpacks/scala/buildpack.toml

Changes GHA release scripts to login to DockerHub and point buildpack metadata to DockerHub repositories instead of AWS ECR ones. The meta-buildpack dependencies remain unchanged for now - after releasing the non-meta buildpacks to DockerHub, the meta-buildpacks will be changed to point at these.
Repository secrets are already added, ECR credentials will be removed once this PR has been merged and has been confirmed to be working.
Ref: GUS-W-13183203

Migrate to DockerHub

---

meta-buildpacks/java-function/CHANGELOG.md
meta-buildpacks/java-function/buildpack.toml
meta-buildpacks/java-function/package.toml
meta-buildpacks/java/CHANGELOG.md
meta-buildpacks/java/buildpack.toml
meta-buildpacks/java/package.toml
meta-buildpacks/scala/CHANGELOG.md
meta-buildpacks/scala/buildpack.toml
meta-buildpacks/scala/package.toml

Switching to DockerHub from ECR as well as releasing new buildpacks (`heroku/sbt` and `heroku/scala`) made it necessary to change some metadata for our meta-buildpacks. This PR fixes meta-buildpacks with the correct Docker URLs, versions and CHANGELOG entries.
Ref: GUS-W-13183203

Update meta-buildpacks for DockerHub migration

---

buildpacks/jvm-function-invoker/CHANGELOG.md
buildpacks/jvm-function-invoker/buildpack.toml
buildpacks/jvm/CHANGELOG.md
buildpacks/jvm/buildpack.toml
buildpacks/maven/CHANGELOG.md
buildpacks/maven/buildpack.toml
buildpacks/sbt/CHANGELOG.md
buildpacks/sbt/buildpack.toml

Most buildpacks already had `stack = *` set, making this a no-op from the users point of view. Also cleans up supported stacks for the `jvm` buildpack, see CHANGELOG for details.
Ref: GUS-W-13204678

Use `*` stack where possible

---

buildpacks/maven/CHANGELOG.md
buildpacks/maven/src/main.rs

At Salesforce, we're trying to use the `heroku/maven` buildpack outside of the standard heroku builder images. Unfortunately, `which` is not in the base image which causes the `mvn` binary to fail while it's trying to find the java command:
```
[builder] [Executing Maven]                                                                                                                                                                                                                                                       
[builder] $ mvn -DskipTests clean install …
```

maven buildpack environment configuration

---

meta-buildpacks/java-function/package.toml
meta-buildpacks/java/package.toml
meta-buildpacks/scala/package.toml

`libcnb` `0.13.0` introduced support for referencing local libcnb buildpacks in `package.toml`. This PR makes use of them.

Use libcnb URIs in package.toml files

---

.github/workflows/release-new.yml

Changes to the workflow to use the extra properties exposed during the `detect` workflow.  I.e.;
* `[buildpacks]` 
* `buildpack_id`
* `buildpack_version`
* `buildpack_dir`
* `buildpack_artifact_prefix`
* `docker_repository`
* `version`
Depends on https://github.com/heroku/languages-github-actions/pull/32

Uses the expanded properties exposed by the detect workflow

---

.gitmodules

Some of the Git submodules previously used SSH instead of HTTPS, which:
- Causes errors in environments where SSH auth isn't configured (such as when people prefer to use HTTPS auth for GitHub, but use a different SSH key for other use-cases, and use a wildcard in the SSH config).
- Is unnecessary, given these are public repos so don't need auth to read.
- Was inconsistent, given that some of the Git submodules already used HTTPS.
This fixes the following errors I get locally:
```
$ git submodule update
Cloning into '/Users/emorley/src/buildpacks-jvm/buildpacks/maven/test-apps/heroku-java-getting-started'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.
```
GUS-W-13745392.

Use HTTPS instead of SSH for Git submodules

---

buildpacks/jvm/CHANGELOG.md
buildpacks/jvm/src/main.rs

Replacement for #545, see code comments for rationale.
Closes GUS-W-13829430

Do not require `jdk` when `system.properties` is missing

---

Cargo.lock
buildpacks/maven/CHANGELOG.md
buildpacks/maven/Cargo.toml
buildpacks/maven/README.md
buildpacks/maven/buildpack.toml
buildpacks/maven/src/errors.rs
buildpacks/maven/src/layer/maven.rs
buildpacks/maven/src/main.rs
buildpacks/maven/src/util.rs
buildpacks/maven/tests/integration/versions.rs

The list of supported Maven versions that are being installed only contained versions with security issues. Most notably [CVE-2022-29599](https://nvd.nist.gov/vuln/detail/CVE-2022-29599). This PR removes these versions as valid versions and adds the most recent `3.x` version of Maven as the only supported (and therefore default) version.
- Update README with updated info about available Maven versions and the default.
- Remove integration tests for now unsupported versions.
- Use Apache's repository for downloading of the Maven distribution, this makes it easier to add  new supported versions in the future.
- These tarballs are different from the ones installed previously. We no longer need to normalize the contents, but now need to strip the first component since it contains the version …

Remove vulnerable Maven versions, add support for 3.9.4

---

Cargo.lock
Cargo.toml
buildpacks/jvm-function-invoker/tests/integration/smoke.rs
buildpacks/sbt/tests/integration/sbt_at_launch.rs
shared-test/src/lib.rs

Upgrade to libcnb `0.14.0`, required only minor changes to a couple of tests but a lot of transitive dependencies are gone now :)

Upgrade to libcnb 0.14.0

---

.gitignore

This is the new default `cargo libcnb package` directory as of libcnb-cargo 0.14.0.

Add libcnb-cargo's default output directory to `.gitignore`

---

Cargo.toml

So that any refreshes to `Cargo.lock` don't cause libcnb to get update to an in-range version (since libcnb is such an integral part of buildpack behaviour).
This is the approach now used by the other CNBs.

Set an explicit libcnb dependency version

---

buildpacks/sbt/tests/integration/main.rs
meta-buildpacks/java/CHANGELOG.md
meta-buildpacks/java/buildpack.toml
meta-buildpacks/java/package.toml
meta-buildpacks/scala/CHANGELOG.md
meta-buildpacks/scala/buildpack.toml
meta-buildpacks/scala/package.toml

Since there has been a new Procfile CNB release:
https://github.com/heroku/procfile-cnb/releases/tag/v2.0.1
https://github.com/heroku/procfile-cnb/compare/v2.0.0...v2.0.1
Also:
- Uses an explicit Procfile CNB version in tests, to prevent test failures when the builder image contains multiple versions (which is the cause of the [CI failures](https://github.com/heroku/buildpacks-jvm/actions/runs/5923710055/job/16071591887#step:8:105) currently seen on `main`).
- Switches the buildpack URI to using the image SHA256, for parity with the URI used in `heroku/builder`.
GUS-W-13982665.

Update Procfile CNB to v2.0.1

---

Cargo.toml
buildpacks/maven/src/main.rs

Fix new Clippy lint failures

---

Cargo.toml
buildpacks/sbt/Cargo.toml

Switches to the [newer resolver](https://doc.rust-lang.org/cargo/reference/resolver.html#feature-resolver-version-2) for the workspace after fixing `sbt`'s dependencies to work with the new resolver.
GUS-W-14109413

Switch to `workspace.resolver=2`

---

buildpacks/jvm/tests/integration/versions.rs

Since the `heroku/buildpacks:20` image is about to be deprecated, and has been replaced by the newly added `heroku/builder:20` for those that need to use a Heroku-20 based builder.
The build and run images used by `heroku/builder:20` are the same as those used by `heroku/buildpacks:20` - the only differences between the builders are the included buildpacks (which is somewhat irrelevant for these integration tests, since the buildpack under test will be injected instead).
The smoke tests in the `heroku/builder` GitHub repo are still testing against all image variants (until such time as we make the legacy images error with an EOL message), so we still have test coverage against them.
See:
https://github.com/heroku/builder/pull/394
https://salesforce.quip.com/0JtbAYiWZYk6
GUS-W-14186015.

Switch tests from `heroku/buildpacks:20` to `heroku/builder:20`

---

Cargo.lock
Cargo.toml
buildpacks/gradle/tests/integration/main.rs
buildpacks/jvm-function-invoker/tests/integration/smoke.rs
buildpacks/maven/tests/integration/main.rs
buildpacks/sbt/tests/integration/main.rs

This also required updating `toml` to 0.8 to prevent a type mismatch error due to the `jvm-function-invoker` buildpack using `libherokubuildpack::toml::toml_select_value` (which itself  is now using toml 0.8).
https://github.com/heroku/libcnb.rs/releases/tag/v0.15.0
https://github.com/heroku/libcnb.rs/compare/v0.14.0...v0.15.0
GUS-W-14354898.

Update libcnb from 0.14.0 to 0.15.0

---

buildpacks/jvm/buildpack.toml

Missed during the regex search and replace used for #603.
GUS-W-14121598.

Fix release metadata for `heroku/jvm`

---

meta-buildpacks/java/CHANGELOG.md
meta-buildpacks/java/buildpack.toml
meta-buildpacks/java/package.toml
meta-buildpacks/scala/CHANGELOG.md
meta-buildpacks/scala/buildpack.toml
meta-buildpacks/scala/package.toml

Previously the `heroku/procfile` buildpack was included within the `heroku/java` and `heroku/scala` composite buildpacks.
Whilst this is convenient (it saves having to add the Procfile CNB manually), this approach has a number of issues:
- If an app uses multiple languages (eg `heroku/nodejs` and `heroku/java`), the Procfile CNB will end up being run multiple times, and potentially with different versions of the Procfile buildpack.
- It means multiple places need updating after Procfile CNB releases, and means the builder image can end up containing several different versions of the Procfile buildpack.
After this change, the `heroku/procfile` CNB is no longer included in the `heroku/java` and `heroku/scala` composite buildpacks, and instead will be included in the Heroku builder image …

Remove `heroku/procfile` from `heroku/java` and `heroku/scala`

---

Cargo.toml
buildpacks/gradle/Cargo.toml
buildpacks/jvm-function-invoker/Cargo.toml
buildpacks/jvm/Cargo.toml
buildpacks/maven/Cargo.toml
buildpacks/sbt/Cargo.toml
shared-test/Cargo.toml
shared/Cargo.toml

Both Dependabot and `cargo-edit`'s `cargo upgrade` don't seem to handle dependencies being specified in the Cargo workspace `Cargo.toml` and inherited by individual crates very well.
As such, this switches back to specifying those dependencies explicitly in each crate. Dependabot always updates dependencies across all crates, so they will still stay in sync.
Hopefully this change will fix:
```
updater | 2023/11/17 15:48:21 INFO <job_751330580> No update possible for libcnb 0.15.0
```
Seen in:
https://github.com/heroku/buildpacks-jvm/network/updates/751330580
I've left the local shared crate dependencies as workspace-defined, since Dependabot or `cargo-edit` doesn't need to update those, since they are path-only dependencies.
Lastly, the lists of dependencies have been sorted …

Switch away from workspace-defined dependencies

---

Cargo.toml
buildpacks/gradle/src/gradle_command/dependency_report.rs
buildpacks/gradle/src/gradle_command/mod.rs
buildpacks/gradle/src/gradle_command/tasks.rs
buildpacks/gradle/src/main.rs
buildpacks/gradle/tests/integration/main.rs
buildpacks/jvm-function-invoker/src/layers/bundle.rs
buildpacks/jvm-function-invoker/src/main.rs
buildpacks/jvm/src/bin/heroku_database_env_var_rewrite.rs
buildpacks/jvm/src/bin/heroku_metrics_agent_setup.rs
buildpacks/jvm/src/main.rs
buildpacks/maven/src/layer/maven.rs
buildpacks/maven/src/main.rs
buildpacks/maven/tests/integration/customization.rs
buildpacks/maven/tests/integration/main.rs
buildpacks/sbt/src/main.rs
buildpacks/sbt/tests/integration/main.rs
clippy.toml
shared/src/fs.rs

Enables some off-by-default lints that we already use in the `libcnb.rs` repository.
https://doc.rust-lang.org/rustc/lints/listing/allowed-by-default.html#unreachable-pub
https://doc.rust-lang.org/rustc/lints/listing/allowed-by-default.html#unsafe-code
https://rust-lang.github.io/rust-clippy/master/index.html#/panic_in_result_fn
https://rust-lang.github.io/rust-clippy/master/index.html#/unwrap_used
GUS-W-14523834.

Enable additional rustc and Clippy lints

---

Cargo.toml
buildpacks/gradle/Cargo.toml
buildpacks/jvm-function-invoker/Cargo.toml
buildpacks/jvm/Cargo.toml
buildpacks/maven/Cargo.toml
buildpacks/sbt/Cargo.toml
shared-test/Cargo.toml
shared/Cargo.toml

As of Cargo 1.75 the `version` property in `Cargo.toml` is now optional, and if omitted is the same as having specified `version = "0.0.0"` and `publish = false`:
https://github.com/rust-lang/cargo/blob/master/CHANGELOG.md#cargo-175-2023-12-28
https://doc.rust-lang.org/cargo/reference/manifest.html#the-version-field
Therefore for crates that we do not publish, we can now remove both the `version` and `publish` properties, avoiding the need for the fake `0.0.0` version that differs from the actual buildpack version in `buildpack.toml`.
GUS-W-14821120.

Simplify Cargo metadata for `publish = false` crates

---

buildpacks/jvm/CHANGELOG.md
buildpacks/jvm/src/bin/heroku_dynamic_jvm_opts.rs

In addition to porting the changes from the existing Heroku JVM buildpack, the defaults for `Performance-M` and `Performance-L` are also removed. Their previous defaults have either the same effect as `XX:MaxRAMPercentage=80.0` or are _very_ close to it. We didn't change this for the existing buildpacks, but for CNBs this is a low-risk change that streamlines the defaults we use.
Ref: GUS-W-14846033

Reduce JVM flags to `-XX:MaxRAMPercentage=80.0` for non Eco, Basic and Standard-*X dynos

---

CODE_OF_CONDUCT.md

This adds the [Salesforce standard OSS CODE_OF_CONDUCT.md](https://github.com/salesforce/oss-template/blob/main/CODE_OF_CONDUCT.md).

Add Salesforce Standard OSS CODE_OF_CONDUCT.md

---

buildpacks/gradle/tests/integration/main.rs
buildpacks/sbt/tests/integration/main.rs

The Procfile CNB has just moved Docker Hub repo:
https://github.com/heroku/buildpacks-procfile/pull/219
Instead of updating the repo URL used in the tests, I've switched the tests to use the Procfile CNB from the builder image instead.
This is now safe to do, since there is now only ever one Procfile version in the builder after:
https://github.com/heroku/buildpacks-jvm/pull/608
https://github.com/heroku/buildpacks-nodejs/pull/696
Using the Procfile version from the builder has a few advantages:
- Greater parity with what will be used in production
- Less churn from us needing to bump the versions here
- Faster, since saves having to pull a new image from Docker Hub
There is the chance of breakage, should the upstream Procfile CNB make a breaking change, however, that should be very rare …

Use the Procfile CNB from the builder in tests

---

buildpacks/gradle/src/gradle_command/dependency_report.rs

Removing it now since it causes linting errors with `clippy 0.1.78 (9b00956e 2024-04-29)`.

Remove unused `ParseError`

---

buildpacks/gradle/CHANGELOG.md
buildpacks/gradle/src/errors.rs
buildpacks/jvm/CHANGELOG.md
buildpacks/jvm/src/errors.rs
buildpacks/maven/CHANGELOG.md
buildpacks/maven/src/errors.rs
buildpacks/maven/tests/integration/misc.rs
buildpacks/sbt/CHANGELOG.md
buildpacks/sbt/src/errors.rs
shared/src/log.rs

Currently, some error messages suggest to open a Heroku support ticket. This behaviour was inherited from the existing Heroku buildpacks.
However, this doesn't make sense for our CNBs as they are not specific to the Heroku platform and can be used outside of it. Instead, users should open an issue on GitHub if they encounter a problem they need help with.
Otherwise, this PR does not change the error messages. I want to streamline errors between JVM buildpacks as well as adding stricter tests for them. But this is not the PR for that.

Remove Heroku support links on errors

---

.github/dependabot.yml

Getting started guide test fixtures as well as sbt-extras are added as a Git submodule in this repository.
Fixes #601.

Enable dependabot for Git submodules

---

Cargo.lock
buildpacks/jvm/CHANGELOG.md
buildpacks/jvm/Cargo.toml
buildpacks/jvm/src/constants.rs
buildpacks/jvm/src/main.rs
buildpacks/jvm/src/salesforce_functions.rs
buildpacks/jvm/test-apps/java-default-app/pom.xml
buildpacks/jvm/test-apps/salesforce-functions-app/pom.xml
buildpacks/jvm/test-apps/salesforce-functions-app/project.toml
buildpacks/jvm/tests/integration/versions.rs
buildpacks/maven/test-apps/simple-http-service-groovy-polyglot/system.properties

Previously, the OpenJDK buildpack installed OpenJDK 8 when no other version was explicitly configured via `system.properties`. This PR changes the behaviour to use the latest LTS version instead of Java 8. In addition, a warning is now displayed when the default version is being used, nudging users to explicitly configure the OpenJDK version.
Since the buildpack is still used by Salesforce functions, there is a conditional that reverts back to the old policy of installing OpenJDK 8 by default if the application is detected to be a Salesforce function (via data in the `project.toml` file  that is mandatory on Salesforce functions).
- A warning will now be shown when the OpenJDK version is not explicitly configured for an application.
- This buildpack now installs the latest long-term …

Change default OpenJDK version

---

.github/workflows/ci.yml

See: https://github.com/heroku/buildpacks-python/pull/204
Also accidentally ninja-ed in an update to one of the Git submodules without code changes and decided to leave it in.

Switch to the GA GitHub Actions ARM runners

---

buildpacks/gradle/buildpack.toml
buildpacks/jvm-function-invoker/buildpack.toml
buildpacks/jvm/buildpack.toml
buildpacks/maven/buildpack.toml
buildpacks/sbt/buildpack.toml

With the release of `pack` `v0.34.2` (GHA PR: https://github.com/heroku/buildpacks-jvm/pull/689) the previously used workaround of having a stacks table with `id = *` in each `buildpack.toml` can be finally removed.

Remove stacks table from buildpack.toml files

---

.github/workflows/check_changelog.yml
.github/workflows/ci.yml

Switches to the new GitHub Actions runner groups to:
1. Avoid the rate limit issues mentioned in: https://github.com/heroku/buildpacks-go/pull/283
2. To update to Ubuntu 24.04
Also pre-pulls the builder and run images to prevent duplicate pulls and impact on rate limits, as mentioned in:
https://github.com/heroku/buildpacks-python/pull/223
This will resolve the rate limit errors seen here:
https://github.com/heroku/buildpacks-jvm/actions/runs/9856103370/job/27212380187#step:8:83
See also:
https://salesforce.quip.com/bu6UA0KImOxJ#temp:C:GZR57becb9df8d94f80b132168fd
https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2404-Readme.md
GUS-W-16238120.

Prevent issues with Docker Hub rate limits in CI

---

buildpacks/jvm/src/bin/heroku_database_env_var_rewrite.rs
buildpacks/maven/src/errors.rs
buildpacks/maven/src/layer/maven.rs
buildpacks/maven/src/main.rs

Remove `unwrap` usages

---

Cargo.lock
Cargo.toml
buildpacks/gradle/src/layers/gradle_home.rs
buildpacks/gradle/src/main.rs
buildpacks/jvm-function-invoker/src/layers/bundle.rs
buildpacks/jvm-function-invoker/src/layers/opt.rs
buildpacks/jvm-function-invoker/src/layers/runtime.rs
buildpacks/jvm-function-invoker/src/main.rs
buildpacks/jvm/src/layers/openjdk.rs
buildpacks/jvm/src/layers/runtime.rs
buildpacks/jvm/src/main.rs
buildpacks/maven/src/layer/maven.rs
buildpacks/maven/src/layer/maven_repo.rs
buildpacks/maven/src/main.rs
buildpacks/sbt/src/layers/dependency_resolver_home.rs
buildpacks/sbt/src/layers/sbt_boot.rs
buildpacks/sbt/src/layers/sbt_extras.rs
buildpacks/sbt/src/layers/sbt_global.rs
buildpacks/sbt/src/main.rs
shared/Cargo.toml
shared/src/env.rs
shared/src/lib.rs

A straightforward port of the existing layer implementations to the new struct-based API. Potential improvements to the layer implementations that are now possible with the new API are not part of the PR.

Migrate to struct layer API

---

.github/CODEOWNERS

To prevent team review requests for Dependabot PRs like:
- https://github.com/heroku/buildpacks-jvm/pull/712
- https://github.com/heroku/buildpacks-jvm/pull/722
- https://github.com/heroku/buildpacks-jvm/pull/723
- https://github.com/heroku/buildpacks-jvm/pull/724

Add Git submodule directories to CODEOWNERS

---

buildpacks/gradle/CHANGELOG.md
buildpacks/gradle/src/errors.rs
buildpacks/gradle/src/framework.rs
buildpacks/gradle/src/main.rs

- The buildpack will add a default process type if a supported framework is detected and the expected build output is found. This mirrors the same feature from the Maven buildpack. ([#726](https://github.com/heroku/buildpacks-jvm/pull/726))
- Support for the Micronaut and Quarkus frameworks. Both previously worked with the buildpack but required some configuration. Unless heavily customized, no build task needs to be specified anymore. ([#726](https://github.com/heroku/buildpacks-jvm/pull/726))

Improve framework support

---

buildpacks/jvm/CHANGELOG.md
buildpacks/jvm/openjdk_inventory.toml
buildpacks/jvm/test-apps/java-22-app/system.properties
buildpacks/jvm/test-apps/java-23-app/system.properties
buildpacks/jvm/tests/integration/versions.rs

Add OpenJDK 23 support

---

.github/CODEOWNERS

In #725 the Git submodules directories were added to CODEOWNERS to try and reduce PR review noise.
However, the languages team alias was still requested for review in #733 and #734.
I suspect this might be due to the trailing slash for these entries in CODEOWNERS - since if you look at the diff view for one of those PRs, they are unsurprisingly tracked as a flat file with a reference, not a directory, eg:
https://patch-diff.githubusercontent.com/raw/heroku/buildpacks-jvm/pull/733.diff

Update CODEOWNERS for Git submodules

---

Cargo.lock
buildpacks/jvm/Cargo.toml
buildpacks/jvm/src/layers/openjdk.rs
buildpacks/jvm/src/main.rs
buildpacks/jvm/src/openjdk_artifact.rs

Prefer using the [recently migrated](https://github.com/heroku/libcnb.rs/pull/861) `inventory` module in `libherokubuildpack` version `0.24.0`.

Prefer libherokubuildpack inventory module

---

buildpacks/jvm/CHANGELOG.md
buildpacks/jvm/src/constants.rs
buildpacks/jvm/tests/integration/main.rs
buildpacks/jvm/tests/integration/overlay.rs

The `heroku/jvm` buildpack used the wrong directory as the source for the JDK overlay. This PR fixes that and adds tests for the JDK overlay.
Fixes #738

Fix JDK overlay directory, add tests

---

.github/workflows/ci.yml
CONTRIBUTING.md
buildpacks/jvm/CHANGELOG.md
shared/src/lib.rs

This prints the getting started guides on CI so a reviewer can inspect the impact of changes to the visual style including ANSI colorization.

[Stacked] Print getting started guides in CI

---

.github/workflows/ci.yml
Cargo.toml
buildpacks/gradle/src/main.rs
buildpacks/jvm-function-invoker/src/main.rs
buildpacks/jvm/src/main.rs
buildpacks/maven/src/main.rs
buildpacks/sbt/src/main.rs

This PR adds a new GHA job that uploads an HTML report of unit test code coverage to the GHA run. It's separated from the normal unit test runs by design as the coverage report requires nightly Rust. Should the coverage report fail to generate, all other jobs still run as usual. Failure to generate the report will not block PRs.
This setup uses https://github.com/taiki-e/cargo-llvm-cov to use [llvm-cov](https://llvm.org/docs/CommandGuide/llvm-cov.html) with Cargo. 
Buildpacks usually contain a lot of code that is not unit-testable as it shells out to other programs or is heavy on FS interactions. Code that is not unit-testable can be excluded by using an attribute like so:
```rust
#[cfg_attr(coverage_nightly, coverage(off))]
fn buildpack_code() {}
```
The final report will be appended to …

Add cargo-llvm-cov test coverage reports in CI

---

buildpacks/jvm-function-invoker/src/error.rs
buildpacks/jvm-function-invoker/src/layers/bundle.rs
buildpacks/jvm/src/bin/heroku_database_env_var_rewrite.rs
shared-test/src/lib.rs

Fixes:
```
warning: this `continue` expression is redundant
--> shared-test/src/lib.rs:52:21
|
52 |                     continue;
|                     ^^^^^^^^
|
= help: consider dropping the `continue` expression
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_continue
= note: `-W clippy::needless-continue` implied by `-W clippy::pedantic`
= help: to override `-W clippy::pedantic` add `#[allow(clippy::needless_continue)]`
warning: unnecessary semicolon
--> buildpacks/jvm-function-invoker/src/error.rs:115:6
|
115 |     };
|      ^ help: remove
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#unnecessary_semicolon
= note: `-W clippy::unnecessary-semicolon` implied by `-W …
```

Fix lint errors on newer Rust

---

Cargo.lock
buildpacks/gradle/CHANGELOG.md
buildpacks/gradle/Cargo.toml
buildpacks/jvm-function-invoker/CHANGELOG.md
buildpacks/jvm-function-invoker/Cargo.toml
buildpacks/jvm/CHANGELOG.md
buildpacks/jvm/Cargo.toml
buildpacks/maven/CHANGELOG.md
buildpacks/maven/Cargo.toml
buildpacks/sbt/CHANGELOG.md
buildpacks/sbt/Cargo.toml
shared-test/Cargo.toml
shared/Cargo.toml

This enables `libcnb`'s `trace` feature, which means traces, spans, and events are written to OpenTelemetry export files on disk in the ephemeral build container, which can then be read by the Heroku build system or when debugging locally with Pack (so long as a suitable `--volume` mount has been configured).
See:
https://github.com/heroku/libcnb.rs/pull/723
Closes #768.
GUS-W-15148616.

Enable libcnb tracing

---

.github/workflows/ci.yml

Since Heroku-20 is has reached end-of-life:
https://devcenter.heroku.com/changelog-items/3230

Remove testing for heroku-20 based builders

---

buildpacks/gradle/CHANGELOG.md
buildpacks/gradle/src/layers/gradle_home.rs

The layer that contains `GRADLE_USER_HOME` was accidentally included in the run image. This layer contains, besides other things, the dependency cache. This will cause the size of the run image to be unnecessarily large. Modern frameworks copy all required dependencies into an uber-jar and should an application need those dependencies at runtime they should be copied during the build to an appropriate directory.
This behaviour is in line with Heroku's classic buildpack for Gradle.
- Gradle home layer (referenced by `GRADLE_USER_HOME`) is no longer available in the run image. It was accidentally included in an earlier version of the buildpack. Applications should not rely on Gradle during runtime. ([#811](https://github.com/heroku/buildpacks-jvm/pull/811)) …

Remove Gradle home from launch image

---

.github/CODEOWNERS

So that review from PRs like #818 are requested from the language owner, rather than the whole team.
This is the CNB equivalent of https://github.com/heroku/heroku-buildpack-jvm-common/pull/375.

Update CODEOWNERS for `inventory.json`

---

.github/CODEOWNERS

Since `inventory.json` doesn't exist.
Ensures the correct reviewer is set for PRs like #840.

Correct the OpenJDK inventory filename in CODEOWNERS

---

buildpacks/gradle/test-apps/gradle-env-test/system.properties
buildpacks/jvm/CHANGELOG.md
buildpacks/jvm/src/constants.rs
buildpacks/jvm/tests/integration/versions.rs

Default OpenJDK major version changed from `21` to `25`. This only applies if no version is specified in `system.properties`. This is in-line with the policy that the latest LTS release is always the default version installed.
Refs: 
- https://github.com/heroku/heroku-buildpack-jvm-common/pull/396
- GUS-W-19636327

Change OpenJDK default major version to 25
